apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ciberguate-dev
resources:
  - ../../base
images:
  - name: ciberguate-frontend
    newName: 631412642574.dkr.ecr.us-east-1.amazonaws.com/ciberguate-frontend
    newTag: 3ad40b7b9bdc001bc33192e9a49ebf8a5028a48c
  - name: ciberguate-backend
    newName: 631412642574.dkr.ecr.us-east-1.amazonaws.com/ciberguate-backend
    newTag: 3ae3b61fc3808712fb11e40ec95161de099d9cf3
replicas:
  - name: frontend
    count: 1
  - name: backend
    count: 1
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ciberguate-config
    behavior: replace
    literals:
      - BACKEND_URL=http://backend:8000
      - CORS_ORIGINS=http://localhost:3000
      - SEED_DATA=true
labels:
  - pairs:
      environment: dev
