apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ciberguate-dev
resources:
  - ../../base
images:
  - name: ciberguate-frontend
    newName: 631412642574.dkr.ecr.us-east-1.amazonaws.com/ciberguate-frontend
    newTag: 0d5156ff190673b9e3f9859a518d326e5a28dad3
  - name: ciberguate-backend
    newName: 631412642574.dkr.ecr.us-east-1.amazonaws.com/ciberguate-backend
    newTag: 670a5ca7dfefd3e25f0d713e556e0b36d4218620
replicas:
  - name: frontend
    count: 1
  - name: backend
    count: 1
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ciberguate-config
    behavior: replace
    literals:
      - BACKEND_URL=http://backend:8000
      - CORS_ORIGINS=http://localhost:3000
      - SEED_DATA=true
      - AUTOMATION_INTERVAL_MS=60000
      - OPENAI_MODEL=gpt-5-mini
      - OIDC_ISSUER=
      - OIDC_CLIENT_ID=
      - OIDC_REDIRECT_URI=https://100.49.206.62.nip.io/oauth/callback
labels:
  - pairs:
      environment: dev
