apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ciberguate
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port: { number: 8000 }
          - path: /health
            pathType: Exact
            backend:
              service:
                name: backend
                port: { number: 8000 }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port: { number: 3000 }
