apiVersion: v1
kind: Secret
metadata:
  name: ciberguate-secrets
type: Opaque
stringData:
  POSTGRES_DB: ciberguate
  POSTGRES_USER: ciberguate
  POSTGRES_PASSWORD: REEMPLAZAR_DESDE_AWS_SECRETS_MANAGER
  DATABASE_URL: postgresql://ciberguate:REEMPLAZAR_DESDE_AWS_SECRETS_MANAGER@postgres:5432/ciberguate
